on: push
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/streamwest-1629/latex:ubuntu20.04
          file: dockerfile
          build_args: |
            baseimage=ubuntu:20.04
